feat(test): add mock clock API
libp2p/go-flow-metrics pull request #18
Opened 2022-06-30 15:17 UTC by schomatis

Went with a more specialized `UseMockClock` API to clearly signal this is for tests and not something you normally mess with but can revert to the more general `SetClock` if preferred.

Closes https://github.com/libp2p/go-flow-metrics/issues/17.

2022-06-30 15:21 UTC, marten-seemann requested changes

2022-06-30 15:21 UTC, marten-seemann commented on sweeper.go
> +	clockMu sync.Mutex
You don't need a mutex if you're only allowing the setting before any meters are added.

2022-06-30 15:21 UTC, marten-seemann commented on sweeper.go
> +func UseMockClock() *clock.Mock {
This should be a `SetClock(clock)`, so users can inject your own implementation. No need to only allow the use of one specific clock implementation.

2022-06-30 15:27 UTC, schomatis commented on sweeper.go
> +	clockMu sync.Mutex
How am I allowing that? By documentation you mean? In any case this mutex is used twice in the entire test flow so its performance impact is negligible.

2022-06-30 15:28 UTC, schomatis commented
@Stebalien PTAL

2022-06-30 15:29 UTC, marten-seemann commented on sweeper.go
> +	clockMu sync.Mutex
Yes, it's part of the API contract. It's invalid to use the API in any other way, so we don't need the mutex.

2022-06-30 15:31 UTC, marten-seemann commented
Next step will be to use this mock clock in all the test here that currently do `time.Sleep`s. We can do that in a follow-up PR, if you prefer.

2022-06-30 15:31 UTC, schomatis commented on sweeper.go
> +	clockMu sync.Mutex
That's valid, but it's basically free to add this sanity check to improve UX. Still, if you want it gone I'll remove it.

2022-06-30 15:32 UTC, schomatis commented
Yes, let's land this first please.

2022-06-30 15:34 UTC, marten-seemann commented on sweeper.go
> +func UseMockClock() *clock.Mock {
We don't need to expose this API. This can trivially be done in the test case itself.

2022-06-30 15:37 UTC, schomatis commented on sweeper.go
> +func UseMockClock() *clock.Mock {
Yes, but will end up duplicating code both here and in the consumer later. I also can remove this but I'm not sure what is the rationale for wanting it gone; what's the cost we're trying to reduce? (I'm not challenging the request but want to better understand the review rationale for this and future PRs.)

2022-06-30 15:39 UTC, schomatis commented
@marten-seemann @Stebalien It seems running the tests many times (`--count 2`) does keep some global/static context (and hence the clock). I had a sanity check to enforce the mock clock was being set only once but I think I'll have to remove it then. Flag if there's an alternative as I'd prefer to keep that check.

2022-06-30 15:43 UTC, marten-seemann commented on sweeper.go
> +func UseMockClock() *clock.Mock {
It's part the public API this package exposes, and we're trying to keep that as minimal as possible. Even if it means a little bit of duplicated code in tests (it's just one line more anyway here).

2022-06-30 15:44 UTC, schomatis commented on sweeper.go
> +	clockMu sync.Mutex
Removing all this as part of https://github.com/libp2p/go-flow-metrics/pull/18#issuecomment-1171374375.

2022-06-30 15:45 UTC, marten-seemann commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
Why is this needed? Shouldn't this be precise, now that we control the timing?

2022-06-30 15:47 UTC, schomatis commented
Even removing the overwrite check, running two tests in a row (is it really sequential?) still fails locally:

```
go test . -v --run TestMockClock --count 2

=== RUN   TestMockClock
--- PASS: TestMockClock (0.94s)
=== RUN   TestMockClock
    flow_test.go:204: expected rate 25000 (±1000), got 0
    flow_test.go:204: expected rate 5000 (±200), got 0
    flow_test.go:198: expected total 340000, got 0
--- FAIL: TestMockClock (0.85s)
```

So it seems I'm clearly missing something of how multiple runs of same test share context that I'll need to look closer into.

2022-06-30 15:49 UTC, marten-seemann commented
Did current tests pass with `count=2`?

2022-06-30 15:49 UTC, schomatis commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
That is just a convenience wrapper. You should check with Steven about accuracy; I'm not sure how easy it is to predict the EWMA (specially with missing counts when starting).

2022-06-30 15:58 UTC, schomatis commented
I think anything that is run in the same `go test` call (be it many of the same or each of different tests) use the same context/clock and that is why even remote tests (no `--count` > 1) also fails.

If this is confirmed then the expectation of https://github.com/libp2p/go-flow-metrics/issues/17#issuecomment-1170051652 is clearly unmet and we should re-discuss in the issue how is the mock clock going to be used.

2022-06-30 16:00 UTC, schomatis commented on sweeper.go
> +func UseMockClock() *clock.Mock {
Understood, making it private.

2022-06-30 16:14 UTC, marten-seemann commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
Why would we miss counts? The whole point of using a mock clock is that the behavior is completely deterministic.

2022-06-30 16:27 UTC, Stebalien commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
It will still be approximate, but we can probably reduce the error.

2022-06-30 16:28 UTC, schomatis commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
Deterministic doesn't mean easy to compute. If there's a way that doesn't involve running the tests, failing and then hard-coding exact value I'm fine applying it. You don't miss counts in the sense that some randomness in the Go runtime makes unordered events compute the rate differently, but even with constant samples like in our tests at the start of the weighted average the window is composed of only a few samples. Anyway, I don't know much about this so check all this with Steven please, this is not related to the mock clock implementation itself (which is not even working and what I'm trying to focus on fixing right now).

2022-06-30 16:28 UTC, Stebalien commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
We won't miss counts, but rates are floats and they'll converge on the correct rate over time, but may never actually reach it. Although I guess the float only has so much precision, so we'll probably reach it pretty quickly...

2022-06-30 16:48 UTC, schomatis commented
Yeah, we're definitely sharing the sweeper across tests. Blocking on https://github.com/libp2p/go-flow-metrics/issues/17#issuecomment-1171454243.

2022-06-30 17:12 UTC, Stebalien commented
- You could have a global clock, and mock it in an init.
- You could swap out the globalSweeper on test init/cleanup.

2022-07-01 16:07 UTC, schomatis commented on flow_test.go
> +func checkApproxEq(t *testing.T, rate float64, expected, err int) {
Reduced error margins 10x.

2022-07-01 16:40 UTC, schomatis commented
Having race issues with the swapping, will try some more this approach (with more care of stopping goroutines first) and attempt the alternative if I can't make progress here.

2022-07-05 00:40 UTC, schomatis commented
Added a stop signal when swapping sweepers.

2022-07-07 21:36 UTC, Stebalien reviewed
This probably works, but being able to "stop" adds complexity.

You encountered a race because the `globalSweeper` is by-value. If we make it by-reference, we should be able to replace it without interfering with the previous sweeper (which will die on its own).

2022-07-07 21:36 UTC, Stebalien commented on sweeper.go
> +		}
```suggestion
	for ctx.Err() == nil {
```

2022-07-07 21:36 UTC, Stebalien commented on sweeper.go
> +}
These are testing functions and don't need to be exported.

2022-07-08 09:55 UTC, marten-seemann commented on flow_test.go
> +	checkApproxEq(t, actual.Rate, 25000, 100)
I think I've said this before, but there's no need for approximations. We're using a mock clock, so timing is precise, and so should be the measurement.

2022-07-08 11:06 UTC, marten-seemann commented
I'm getting the impression that this PR is moving in the wrong direction. 
@schomatis, thanks for your work here. I'll be taking over from here on.

2022-07-08 17:56 UTC, schomatis commented on sweeper.go
> +}
The idea would be to use this in https://github.com/libp2p/go-libp2p-core/issues/267 so I think we still want to export this, or something similar to it.

2022-07-08 17:56 UTC, schomatis commented
> If we make it by-reference

That makes sense.

2022-07-08 17:59 UTC, schomatis commented
> I'm getting the impression that this PR is moving in the wrong direction.
@schomatis, thanks for your work here. I'll be taking over from here on.

@marten-seemann Your call. This PR is already passing and I'm aligned with Steven's input, so I'm not sure which wrong direction has this taken. The error margin comment is valid but it's not central to the mock clock implementation (but how we leverage it later), so I prioritized fixing the data race which was the blocker here.

2022-07-09 09:58 UTC, closed without merging