fix(ewma): reduce the chances of fake bandwidth spikes
libp2p/go-flow-metrics pull request #8
Opened 2019-10-16 10:37 UTC by Stebalien

Ignore updates that are less than 100ms. Otherwise, we could attribute a large amount of bandwidth to a very short period of time and get a _huge_ spike.

The next step will be to split writes up into chunks _before_ we get to the meter.

An alternative is to record the amount of data sent and a time. However, the
current system was chosen precisely to avoid repeatedly asking for the time.

2019-10-16 14:04 UTC, raulk commented
This makes me uneasy because it introduces a timing condition that summons another class of bugs. How about we break down the act of recording into two methods?

On Meter, a Prerecord() method that returns a pointerless Recording type that is just a time.Time of when the recording started.

On Recording (value receiver), a Record(float64) performs the actual recording.

The whole thing can incur in zero allocs and overcome the ugliness of asking for time with every recording.

2019-10-17 00:49 UTC, Stebalien commented
> This makes me uneasy because it introduces a timing condition that summons another class of bugs.

We already have a timing condition, this just makes it less of an issue. The problem is:

1. Receive a tick.
2. Read the tick.
3. Pause due to the scheduler.
4. Receive a tick on the channel (but don't read it).
5. Handle the tick first tick.
6. Read and handle the second tick.

The second tick will be _really_ short.

Alternatively, we could switch from a ticker to a timer, resetting it after every tick. But it doesn't _really_ matter much either way.

> How about we break down the act of recording into two methods?
>
> On Meter, a Prerecord() method that returns a pointerless Recording type that is just a time.Time of when the recording started.
>
> On Recording (value receiver), a Record(float64) performs the actual recording.
>
> The whole thing can incur in zero allocs and overcome the ugliness of asking for time with every recording.

Note: I'm not concerned about uglyness, I'm concerned about the _cost_ of getting the time. Getting the time is slower (but not by much) than allocating on Linux and requires a syscall on some systems.

However, we can probably record the last tick time in the "sweeper" loop and use that.

2019-10-17 01:17 UTC, Stebalien commented
Actually, I have no idea how to do this without introducing additional performance penalties on write. The issue is that meters can be updated by _multiple_ writers at the same time.

2019-10-22 22:11 UTC, Stebalien commented
I've pushed a fix for non-monotonic clocks.

2023-11-10 09:36 UTC, marten-seemann requested changes
CI seems very unhappy with this change.

2023-11-10 09:36 UTC, marten-seemann commented on sweeper.go
> +var ewmaRate = time.Second
const?

2023-11-10 16:49 UTC, Stebalien commented on sweeper.go
> +var ewmaRate = time.Second
CI is always unhappy.

2024-02-13 05:43 UTC, merged